/**
 * gen-pages.mjs — the three map levels, GENERATED. Never hand-edit the output.
 *
 *   /                        7 part sections, 16 domain cards
 *   /<domain>/               clusters as cards                    x 16
 *   /<domain>/<cluster>/     every book as a card, live or not    x 85
 *
 * plus four derived artifacts:
 *
 *   src/generated/universe.json    the parsed tree, for anything that needs it
 *   src/generated/nav-labels.json  slug -> label, IMPORTED by the breadcrumb
 *   src/generated/book-slugs.md    293 rows, handed to web chat as knowledge
 *   public/_redirects              re-cluster redirects, header only until used
 *
 * A book's own directory is written by scripts/new-book.mjs, never here.
 *
 * ---------------------------------------------------------------------------
 * WHY nav-labels.json IS IMPORTED RATHER THAN READ
 *
 * The breadcrumb override first called parseUniverse() directly. That works in
 * `dev` and fails in `build`: the component is bundled into dist/.prerender/,
 * so the relative path to context/universe.md resolves against the bundle and
 * throws ENOENT at render time. A build-time file read does not survive
 * bundling into the render context. An imported JSON module does — the bundler
 * inlines it.
 *
 * ---------------------------------------------------------------------------
 * WHY RAW HTML AND NOT <LinkCard>
 *
 * A book that has not been started has NOWHERE TO GO. A <LinkCard> must have an
 * href; saying "not started" by not being a link is more honest than a link
 * that does nothing. So a card is a <div> whose title is an <a> only when the
 * book's directory actually exists on disk.
 *
 * Block containers are <div>, never <p>. Markdown wraps multi-line content in a
 * <p> of its own, and a <p> inside a <p> is invalid HTML that browsers silently
 * restructure — with the build exiting 0 throughout.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, rmSync, readdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseUniverse } from './universe.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'src', 'content', 'docs');
const GENERATED = join(ROOT, 'src', 'generated');

const BANNER =
	'{/* GENERATED by scripts/gen-pages.mjs from context/universe.md. Do not hand-edit. */}';

/*
 * The method pages are `.md`, NOT `.mdx`, and that is a deliberate engineering
 * choice rather than an inconsistency with the rest of the project.
 *
 * They are VERBATIM copies of four hand-written documents in context/, and
 * between them those documents contain 38 bare `<` characters in ordinary prose
 * ("<30% degradation", "d < 0.2", "<BOOK>"). In .mdx every one of those is the
 * start of a JSX tag and a hard build error. In .md it is a literal.
 *
 * The project's ".mdx only" rule governs AUTHORED pages, where the components
 * are the point. Nothing here authors anything: escaping a copy to satisfy a
 * rule aimed at a different problem would mean the published text no longer
 * matches the file it came from, which is the one property these pages have.
 *
 * Consequence to know: no components, and the comment syntax is HTML.
 */
const MD_BANNER =
	'<!-- GENERATED by scripts/gen-pages.mjs from context/. Do not hand-edit: edit the source. -->';

/* --------------------------------------------------------------------------
 * Text
 * ------------------------------------------------------------------------ */

/** HTML-escape, INCLUDING `{`, which MDX reads as the start of an expression. */
const esc = (s) =>
	String(s)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/\{/g, '&#123;')
		.replace(/\}/g, '&#125;');

/**
 * The smallest possible inline-Markdown renderer, for the `why` lines, which
 * carry **bold**, *italic* and `code`.
 *
 * ESCAPES FIRST, then marks up, so nothing in the source file can inject HTML.
 * Handles three constructs and must not grow into a parser.
 */
function inlineMd(raw) {
	let s = esc(raw);
	s = s.replace(/`([^`]+)`/g, '<code>$1</code>');
	s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>'); // bold before italic
	s = s.replace(/\*([^*]+)\*/g, '<em>$1</em>');
	return s;
}

/** Quote and escape in one step. */
const yaml = (v) => JSON.stringify(String(v));

/** Truncate at a word boundary. */
function clamp(s, n) {
	const t = String(s).replace(/\s+/g, ' ').trim();
	if (t.length <= n) return t;
	return t.slice(0, t.lastIndexOf(' ', n)).replace(/[,;:.—-]+$/, '') + '…';
}

/* --------------------------------------------------------------------------
 * Markup
 * ------------------------------------------------------------------------ */

const TIER_LABEL = { core: 'Core', deepen: 'Deepen', reference: 'Reference' };
const WEIGHT_LABEL = { S: 'Short', M: 'Medium', L: 'Long' };
const FLAG_LABEL = {
	caveat: 'Caveat',
	lifelong: 'Lifelong',
	free: 'Free',
	ground: 'My ground',
};
const FLAG_GLYPH = { caveat: '⚠', lifelong: '∞', free: 'Free', ground: 'NP' };

const chip = (cls, text, title) =>
	`<span class="ds-chip ${cls}"${title ? ` title="${esc(title)}"` : ''}>${esc(text)}</span>`;

function bookCard(book, href) {
	const chips = [
		chip(`ds-chip--tier-${book.tier}`, TIER_LABEL[book.tier], `${TIER_LABEL[book.tier]} — see the legend`),
		chip('ds-chip--weight', book.weight, WEIGHT_LABEL[book.weight]),
		...book.flags.map((f) => chip(`ds-chip--flag ds-chip--flag-${f}`, FLAG_GLYPH[f], FLAG_LABEL[f])),
	].join('');

	const title = href
		? `<a class="ds-card__link" href="${href}">${esc(book.title)}</a>`
		: esc(book.title);

	const byline = [book.author, book.edition && `(${book.edition})`].filter(Boolean).join(' ');

	return [
		`<div class="ds-card ds-book${href ? '' : ' ds-card--empty'}" data-tier="${book.tier}" data-weight="${book.weight}">`,
		`<h3 class="ds-card__title">${title}</h3>`,
		byline ? `<div class="ds-card__byline">${inlineMd(byline)}</div>` : '',
		`<div class="ds-card__body">${inlineMd(book.why)}</div>`,
		`<div class="ds-card__meta">${chips}</div>`,
		`</div>`,
	]
		.filter(Boolean)
		.join('\n');
}

function plainCard({ href, title, body, meta }) {
	return [
		`<div class="ds-card${href ? '' : ' ds-card--empty'}">`,
		`<h3 class="ds-card__title">${href ? `<a class="ds-card__link" href="${href}">${esc(title)}</a>` : esc(title)}</h3>`,
		body ? `<div class="ds-card__body">${inlineMd(body)}</div>` : '',
		meta ? `<div class="ds-card__meta">${meta}</div>` : '',
		`</div>`,
	]
		.filter(Boolean)
		.join('\n');
}

const grid = (cards) => `<div class="ds-grid">\n\n${cards.join('\n\n')}\n\n</div>`;

/** Counts, shown as chips. Deliberately NOT a count of books read: the
 *  reconciliation (row 9) puts no reading counter anywhere in the chrome.
 *
 *  A ZERO IS OMITTED, NOT SHOWN. MEASURED 2026-09-01: a cluster with no core
 *  book — real, and not rare; a cluster can be all deepen and reference —
 *  rendered "0 core" beside its two real counts. A count exists to tell you
 *  how much of something there is; "0 core" tells you there is none, which is
 *  what its ABSENCE already says on every other row. Whichever tiers are
 *  actually present still render in their fixed order, so "2 deepen · 1
 *  reference" reads as a complete answer rather than a row with a hole in it.
 */
function tierCounts(books) {
	const n = (t) => books.filter((b) => b.tier === t).length;
	return [
		n('core') && chip('ds-chip--count ds-chip--tier-core', `${n('core')} core`),
		n('deepen') && chip('ds-chip--count ds-chip--tier-deepen', `${n('deepen')} deepen`),
		n('reference') && chip('ds-chip--count ds-chip--tier-reference', `${n('reference')} reference`),
	]
		.filter(Boolean)
		.join('');
}

const LEGEND = [
	'<div class="ds-legend">',
	'<span><b>Core</b> — read it. If only the core is read, the domain is covered.</span>',
	'<span><b>Deepen</b> — after the core, and only when the domain is live.</span>',
	'<span><b>Reference</b> — never cover to cover. Opened against a specific problem.</span>',
	'<span><b>S · M · L</b> — what it costs at thirty minutes a day.</span>',
	'</div>',
].join('\n');

/* --------------------------------------------------------------------------
 * On-disk state — which books have actually been started
 * ------------------------------------------------------------------------ */

function startedBooks() {
	const started = new Set();
	if (!existsSync(DOCS)) return started;
	for (const d of readdirSync(DOCS)) {
		const dd = join(DOCS, d);
		if (!existsSync(dd) || !statSync(dd).isDirectory()) continue;
		for (const c of readdirSync(dd)) {
			const cc = join(dd, c);
			if (!statSync(cc).isDirectory()) continue;
			for (const b of readdirSync(cc)) {
				const bb = join(cc, b);
				if (statSync(bb).isDirectory() && existsSync(join(bb, 'index.mdx')))
					started.add(`${d}/${c}/${b}`);
			}
		}
	}
	return started;
}

/* --------------------------------------------------------------------------
 * The pages
 * ------------------------------------------------------------------------ */

function page({ title, description, body, headTitle }) {
	const fm = [
		'---',
		`title: ${yaml(title)}`,
		`description: ${yaml(description)}`,
		'template: splash',
		'tableOfContents: false',
	];
	if (headTitle) {
		// Starlight builds <title> as "<page> | <site>", which on the home page
		// renders "Readings | Readings".
		fm.push('head:', '  - tag: title', `    content: ${yaml(headTitle)}`);
	}
	fm.push('---');
	return `${fm.join('\n')}\n${BANNER}\n\n${body}\n`;
}

function write(relPath, contents) {
	const full = join(DOCS, relPath);
	mkdirSync(dirname(full), { recursive: true });
	writeFileSync(full, contents);
}

function homePage(u, started) {
	const out = [];
	out.push('<div class="ds-head">');
	out.push(
		'<div class="ds-head__lede">Sixteen areas of a life, eighty-five questions, and two hundred and ninety-three books chosen against them. One book at a time — read, argued with, and acted on.</div>'
	);
	out.push(`<div class="ds-head__meta">${tierCounts(u.books)}</div>`);
	out.push('</div>');
	out.push('');
	out.push(LEGEND);
	out.push('');

	for (const p of u.parts) {
		out.push(`## ${esc(p.name)}`);
		out.push('');
		const cards = p.domains.map((d) => {
			const count = d.clusters.reduce((n, c) => n + c.books.length, 0);
			const live = d.clusters.some((c) =>
				c.books.some((b) => started.has(`${d.slug}/${c.slug}/${b.slug}`))
			);
			return plainCard({
				href: `/${d.slug}/`,
				title: d.displayName,
				body: d.question,
				meta:
					chip('ds-chip--count', `${d.clusters.length} clusters`) +
					chip('ds-chip--count', `${count} books`) +
					(live ? chip('ds-chip--live', 'reading') : ''),
			});
		});
		out.push(grid(cards));
		out.push('');
	}

	/*
	 * The one link to /method/, and it lives at the FOOT of the map rather than
	 * in the top nav. The nav holds the four things reached daily; the method is
	 * read once before the first book. Putting it in the header would cost a slot
	 * on every page for a destination visited twice a year — and it would still
	 * be the wrong place, because the question it answers ("on what authority?")
	 * is one you have after seeing the map, not before.
	 */
	out.push('---');
	out.push('');
	out.push(
		'The [method](/method/) this site reads by — the protocol, the evidence behind it, and the',
		'fourteen places the two disagree — is published in full.',
		''
	);

	return page({
		title: 'Readings',
		headTitle: 'Readings — a personal reading map',
		description:
			'A personal reading map: 16 domains, 85 clusters, 293 books, and what each one is for.',
		body: out.join('\n'),
	});
}

function domainPage(d) {
	const books = d.clusters.flatMap((c) => c.books);
	const out = [];
	out.push('<div class="ds-head">');
	// Same as the cluster eyebrow below: the parent is named, so it is reachable.
	out.push(`<div class="ds-head__eyebrow"><a href="/">${esc(d.partName)}</a></div>`);
	out.push(`<div class="ds-head__lede">${esc(d.question)}</div>`);
	out.push(`<div class="ds-head__meta">${tierCounts(books)}</div>`);
	out.push('</div>');
	out.push('');
	out.push('## Clusters');
	out.push('');
	out.push(
		grid(
			d.clusters.map((c) =>
				plainCard({
					href: `/${d.slug}/${c.slug}/`,
					title: `${c.number} · ${c.name}`,
					body: c.rationale ? clamp(c.rationale, 190) : null,
					meta:
						tierCounts(c.books) +
						(c.crossRefs.length
							? chip('ds-chip--count', `${c.crossRefs.length} cross-listed`)
							: ''),
				})
			)
		)
	);
	return page({
		title: d.displayName,
		description: `${d.question} — ${d.clusters.length} clusters, ${books.length} books.`,
		body: out.join('\n'),
	});
}

function clusterPage(c, d, started) {
	const out = [];
	out.push('<div class="ds-head">');
	/*
	 * THE DOMAIN HALF OF THIS IS A LINK, AND IT WAS NOT UNTIL 2026-09-01.
	 *
	 * A cluster page is the only page in the site with a parent it never names
	 * as somewhere you can go: "MONEY & WEALTH · 10.1" was plain text, so the
	 * only way up was the header's "Map", which returns to the root rather than
	 * to the domain you are standing in. Two levels of the taxonomy link down
	 * and the third did not link back.
	 */
	out.push(
		`<div class="ds-head__eyebrow"><a href="/${d.slug}/">${esc(d.displayName)}</a> · ${esc(c.number)}</div>`
	);
	if (c.rationale) out.push(`<div class="ds-head__lede">${inlineMd(c.rationale)}</div>`);
	out.push(`<div class="ds-head__meta">${tierCounts(c.books)}</div>`);
	out.push('</div>');
	out.push('');

	for (const tier of ['core', 'deepen', 'reference']) {
		const set = c.books.filter((b) => b.tier === tier);
		if (!set.length) continue;
		out.push(`## ${TIER_LABEL[tier]}`);
		out.push('');
		out.push(
			grid(
				set.map((b) => {
					const key = `${d.slug}/${c.slug}/${b.slug}`;
					return bookCard(b, started.has(key) ? `/${key}/` : null);
				})
			)
		);
		out.push('');
	}

	if (c.crossRefs.length) {
		out.push('## Cross-listed here');
		out.push('');
		out.push(
			'<div class="ds-note">Read once, counts twice. The full entry lives in another cluster.</div>'
		);
		out.push('');
		out.push(
			grid(
				c.crossRefs.map((x) =>
					plainCard({
						href: `/${x.resolved.domain}/${x.resolved.cluster}/`,
						title: x.title,
						body: `Full entry in cluster ${x.toCluster}.`,
					})
				)
			)
		);
		out.push('');
	}

	return page({
		title: `${c.number} · ${c.name}`,
		description: c.rationale
			? clamp(c.rationale, 155)
			: `${c.books.length} books on ${c.name.toLowerCase()}, in ${d.displayName}.`,
		body: out.join('\n'),
	});
}

/* --------------------------------------------------------------------------
 * Run
 * ------------------------------------------------------------------------ */

/* --------------------------------------------------------------------------
 * The method pages — context/ published verbatim
 * ------------------------------------------------------------------------ */

/**
 * WHY THESE ARE PUBLISHED AT ALL.
 *
 * The site teaches from books using a method that is itself contestable, and it
 * applies that method to HIS life. A reader — including him in two years — is
 * entitled to see the method, its evidence, and the fourteen places where the
 * two disagree. A protocol you cannot inspect is indistinguishable from a
 * preference.
 *
 * ORDER IS LOAD-BEARING. `reconciliation` is second, immediately after the
 * protocol and before the evidence, because the protocol is WRONG in fourteen
 * places and a reader who stops after page one has read the wrong thing. Every
 * page says so in its own banner.
 *
 * These are copies. `context/` is the source, one direction, always — the same
 * contract that governs a Project knowledge file.
 */
const METHOD = [
	{
		src: 'protocol.md',
		slug: 'protocol',
		order: 1,
		title: 'The reading protocol',
		description: 'The twelve-stage pipeline, as first written. Superseded in fourteen places — read the reconciliation next.',
		note:
			'This is the protocol **as first drafted**, kept whole. It was written before the two ' +
			'evidence reviews below, and they contradict it in fourteen places. ' +
			'[The reconciliation](/method/reconciliation/) is operative wherever they disagree.',
	},
	{
		src: 'reconciliation.md',
		slug: 'reconciliation',
		order: 2,
		title: 'Reconciliation',
		description: 'Fourteen places the protocol and its own evidence disagree, and which side wins. Each row cites both.',
		note:
			'**This page wins.** Where it contradicts [the protocol](/method/protocol/), it is the ' +
			'protocol that is out of date, and every row cites both sides by line number.',
	},
	{
		src: 'evidence/reading.md',
		slug: 'reading',
		order: 3,
		title: 'Evidence — reading',
		description: 'What the research actually supports about reading a book and changing behaviour, with effect sizes and limits.',
		note:
			'A literature review, with its own limits stated at the end. **Effect sizes are quoted ' +
			'where they exist and their absence is stated where they do not** — see ' +
			'[source-rules](/method/) for why that distinction is the whole point.',
	},
	{
		src: 'evidence/reading-with-ai.md',
		slug: 'reading-with-ai',
		order: 4,
		title: 'Evidence — reading with AI',
		description: 'Where an AI multiplies the learning, where it removes it, and the one rule that prevents most of the crutch effect.',
		note:
			'The review this whole system is built against. Its central finding is that the damage ' +
			'was **not** caused by AI errors — it was the crutch.',
	},
];

/**
 * Demote every heading one level so the frontmatter `title` is the only H1, and
 * CLOSE THE GAPS THAT DEMOTION LEAVES.
 *
 * FENCE-AWARE, and that is not paranoia: protocol.md contains 30 fenced blocks,
 * several of which show `# comment` lines and MDX/YAML samples. Demoting inside
 * a fence would silently corrupt a code sample into something that no longer
 * matches the thing it documents.
 *
 * ---------------------------------------------------------------------------
 * WHY IT ALSO NORMALISES, ADDED 2026-09-01
 *
 * The sources are drafts, and a draft uses heading depth for emphasis as often
 * as for structure — `# 🔄 PART 1` for a divider and `### *How I read…*` for a
 * subtitle, three lines apart. Demote both by one and the published page reads
 * H1 → H4, then H2 → H4, which is a broken outline for a screen reader and for
 * anything that builds a document tree.
 *
 * MEASURED 2026-09-01 on the built pages, before this:
 *   /method/                H1 → H3
 *   /method/protocol/       H1 → H4, and H2 → H4 twice
 *   /method/reading/        H1 → H3, and H2 → H4
 *   /method/reading-with-ai/  H1 → H3, and H2 → H4 three times
 *
 * The fix has to be here rather than in `context/`, because those files are the
 * contract and are published VERBATIM — their words are the point, and editing
 * their hashes to satisfy the renderer would be the tail wagging the dog.
 *
 * So each heading is clamped to at most one level deeper than the heading
 * before it, the page title counting as level 1. Relative order is preserved
 * exactly: a source heading that was deeper than its predecessor is still
 * deeper, just never by more than one step. A heading at the same level or
 * shallower is untouched beyond the demotion.
 */
function demoteHeadings(text) {
	let inFence = false;
	let prev = 1; // the frontmatter title
	return text
		.split('\n')
		.map((line) => {
			if (/^\s{0,3}(```|~~~)/.test(line)) {
				inFence = !inFence;
				return line;
			}
			if (inFence) return line;
			const m = /^(#{1,5}) (.*)$/.exec(line);
			if (!m) return line;
			const demoted = m[1].length + 1;
			const level = Math.min(demoted, prev + 1, 6);
			prev = level;
			return '#'.repeat(level) + ' ' + m[2];
		})
		.join('\n');
}

function methodPage(entry) {
	const raw = readFileSync(join(ROOT, 'context', entry.src), 'utf8');

	// Drop the source's own H1 — it becomes the frontmatter title. Everything
	// after it is demoted, so the document keeps its shape one level down.
	const body = demoteHeadings(raw.replace(/^\s*#\s+.*\n/m, '')).trim();

	const fm = [
		'---',
		`title: ${yaml(entry.title)}`,
		`description: ${yaml(entry.description)}`,
		`sidebar:`,
		`  order: ${entry.order}`,
		'---',
	];

	return [
		fm.join('\n'),
		MD_BANNER,
		'',
		`:::note[Source: \`context/${entry.src}\`]`,
		entry.note,
		':::',
		'',
		body,
		'',
	].join('\n');
}

function methodHub() {
	const out = [];
	out.push('<div class="ds-head">');
	out.push('<div class="ds-head__eyebrow">How this site works on itself</div>');
	out.push(
		'<div class="ds-head__lede">The method, its evidence, and the fourteen places the two disagree.</div>'
	);
	out.push('</div>');
	out.push('');
	out.push(
		'A protocol you cannot inspect is indistinguishable from a preference. These four documents',
		'are published verbatim from `context/`, in the order they should be read — **the',
		'reconciliation second, not last**, because the protocol is wrong in fourteen places and a',
		'reader who stops after the first page has read the wrong thing.',
		''
	);
	// The grid's cards are h3. Without a section heading above them the page ran
	// h1 -> h3, measured 2026-09-01. Every other grid on the site already has one.
	out.push('## The documents', '');
	out.push(
		grid(
			METHOD.map((m) =>
				plainCard({
					href: `/method/${m.slug}/`,
					title: m.title,
					body: m.description,
					meta:
						chip('ds-chip--count', `context/${m.src}`) +
						(m.slug === 'reconciliation' ? chip('ds-chip--live', 'operative') : ''),
				})
			)
		)
	);
	out.push('');
	out.push('## What is NOT here');
	out.push('');
	out.push(
		'`context/reader.md` and `context/books/` — who he is and what each book is for him — are',
		'private and stay in the repository. `context/source-rules.md`, `md-spec.md`,',
		'`chapter-spine.md` and `book-spec.md` are machine contracts rather than reading: they say',
		'what a page must contain, not what is true.',
		''
	);
	return page({
		title: 'Method',
		description:
			'The reading protocol, the two evidence reviews behind it, and the fourteen conflicts between them.',
		body: out.join('\n'),
	});
}

const u = parseUniverse();
const started = startedBooks();

// Remove previously generated map pages so a renamed slug cannot leave an
// orphan behind. Only files carrying the banner are removed — a book directory
// is never touched.
let removed = 0;
function pruneGenerated(dir) {
	if (!existsSync(dir)) return;
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		if (statSync(full).isDirectory()) pruneGenerated(full);
		else if (entry === 'index.mdx' && readFileSync(full, 'utf8').includes(BANNER)) {
			rmSync(full);
			removed++;
		}
		// The method pages are .md and carry the HTML-comment banner. Pruned by the
		// same rule so a renamed slug cannot strand an orphan that still builds.
		else if (entry.endsWith('.md') && readFileSync(full, 'utf8').includes(MD_BANNER)) {
			rmSync(full);
			removed++;
		}
	}
}
pruneGenerated(DOCS);
if (existsSync(join(DOCS, 'index.mdx')) && readFileSync(join(DOCS, 'index.mdx'), 'utf8').includes('PLACEHOLDER'))
	rmSync(join(DOCS, 'index.mdx'));

write('index.mdx', homePage(u, started));
let pages = 1;

// The method pages. Written BEFORE the map pages so a failure to read one of
// the four sources aborts the run rather than leaving a half-generated tree.
write(join('method', 'index.mdx'), methodHub());
for (const m of METHOD) write(join('method', `${m.slug}.md`), methodPage(m));
for (const d of u.domains) {
	write(join(d.slug, 'index.mdx'), domainPage(d));
	pages++;
	for (const c of d.clusters) {
		write(join(d.slug, c.slug, 'index.mdx'), clusterPage(c, d, started));
		pages++;
	}
}

mkdirSync(GENERATED, { recursive: true });

// The flat slug -> label map the breadcrumb imports.
const labels = { domains: {}, clusters: {}, books: {} };
for (const d of u.domains) {
	labels.domains[d.slug] = d.displayName;
	for (const c of d.clusters) {
		labels.clusters[`${d.slug}/${c.slug}`] = `${c.number} · ${c.name}`;
		for (const b of c.books) labels.books[`${d.slug}/${c.slug}/${b.slug}`] = b.title;
	}
}
writeFileSync(join(GENERATED, 'nav-labels.json'), JSON.stringify(labels, null, '\t') + '\n');
writeFileSync(join(GENERATED, 'universe.json'), JSON.stringify(u, null, '\t') + '\n');

/**
 * book-slugs.md — handed to web chat as a knowledge file.
 *
 * P7 emits cross-book links on EVERY chapter, and an internal link must be
 * root-absolute and must resolve or the build fails. A chat session can compute
 * the path from this file; it cannot guess a cluster slug.
 */
const slugRows = [
	'# Book slugs — every canonical path in the universe',
	'',
	'GENERATED by scripts/gen-pages.mjs. Do not hand-edit.',
	'',
	'Every internal link to a book is ROOT-ABSOLUTE and looks exactly like the',
	'paths below. A relative `../` chain is a hard build error, never resolved.',
	'A chapter is that path plus `<NN>-<chapter-slug>/`.',
	'',
	'| Book | Author | Path |',
	'| --- | --- | --- |',
];
for (const b of u.books)
	slugRows.push(`| ${b.title} | ${b.author ?? '—'} | \`/${b.domain}/${b.cluster}/${b.slug}/\` |`);
slugRows.push('');
writeFileSync(join(GENERATED, 'book-slugs.md'), slugRows.join('\n'));

/**
 * _redirects — path-level redirects for a book that moves between clusters.
 *
 * Cloudflare Workers static assets support these. They do NOT support
 * domain-level redirects, which is a different thing and is why src/lib/
 * indexing.ts exists.
 *
 * Empty of rules until a book actually moves; the header is the instruction.
 */
const redirects = [
	'# Path-level redirects, for a book that has moved between clusters.',
	'#',
	'# A slug is a URL. Moving a book changes its URL and every inbound link,',
	'# so add a line here rather than accepting the breakage:',
	'#',
	'#   /old-domain/old-cluster/the-book/*  /new-domain/new-cluster/the-book/:splat  301',
	'#',
	'# Verify with `npx wrangler dev` — the only local server that applies this file.',
	'',
];
writeFileSync(join(ROOT, 'public', '_redirects'), redirects.join('\n'));

console.log(`\n  generated from context/universe.md\n`);
console.log(`    pages removed       ${removed}   (map + method, by banner)`);
console.log(`    map pages written   ${pages}   (1 + ${u.domains.length} + ${u.clusters.length})`);
console.log(`    method pages        ${METHOD.length + 1}   (hub + ${METHOD.length} published verbatim from context/)`);
console.log(`    books on cards      ${u.books.length}`);
console.log(`    books started       ${started.size}`);
console.log(`    nav-labels.json     ${Object.keys(labels.domains).length} domains, ${Object.keys(labels.clusters).length} clusters, ${Object.keys(labels.books).length} books`);
console.log(`    book-slugs.md       ${u.books.length} rows`);
console.log('');
